# Site settings
title: Boba.js / space150
email: manderson@space150.com
description: "Boba.js is a small, easily extensible JavaScript library that makes working
with Google Analytics easier."
baseurl: ""
url: "http://boba.space150.com"

# Build settings
markdown: kramdown
permalink: pretty
